config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :admins
  devise_for :user
  root to: 'landing#index'

  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  put '/lead_new' => 'leads#create', as: :new_lead

  mount RailsAdmin::Engine => '/administer', as: 'rails_admin'
  namespace :admin do

    root to: 'leads#index'
    resources :leads, only: [:index]
    resources :users
    resources :burial_plans, only: [:new, :create, :edit, :update]
    get '/upgrade_lead' => 'leads#upgrade_form', as: :lead_upgrade_form
    post '//upgrade_lead' => 'leads#upgrade', as: :lead_upgrade
    get '/call' => 'calls#index', as: :call
    post '/call' => 'calls#create_call'
    get '/call_connect' => 'call_connect#index'
    post '/place_call_connect' => 'call_connect#create', as: :place_call_connect

    devise_scope :admins do
    get '/login'   => 'devise/sessions#new', id: 'login'
    post 'login'   => 'devise/sessions#create'
    delete 'logout'=> 'devise/sessions#destory', id: 'logout'
    end
  end

  namespace :user do
    root to:'users#show'
    resources :after_signup
    resources :burial_plans
    resources :burial_cemetery_plans
    resources :burial_mausoleum_plans
    resources :cremation_plans
    # get '/registration'      => 'users#registration'
    # patch '/registration/update' => 'users#update', as: :registration_update
    get '/plans/new' => 'plans#new', as: :plan_new
    # patch '/burial_plans/update' => 'burial_plans#update', as: :burial_update
    # get '/burial_plans/new' => 'burial_plans#new', as: :burial_new
    # patch '/cremation_plans/update' => 'cremation_plans#update', as: :cremation_update
    # get '/cremation_plans/new' => 'cremation_plans#new', as: :cremation_new
    # get '/burial_cemetery_plan/new' => 'burial_cemetery_plans#new', as: :burial_cemetery_new
    # patch '/burial_cemetery/update' => 'burial_cemetery_plans#update', as: :burial_cemetery_update
    # get '/burial_mausoleum_plan/new' => 'burial_mausoleum_plans#new', as: :burial_mausoleum_new
    # patch '/burial_mausoleum/update' => 'burial_mausoleum_plans#update', as: :burial_mausoleum_update



  devise_scope :user do
    get 'signup'   => 'devise/registrations#new', id: 'signup'
    get '/login'   => 'devise/sessions#new', id: 'login'
    post 'login'   => 'devise/sessions#create'
    delete 'logout'=> 'devise/sessions#destory', id: 'logout'
  end

  end


  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/views/landing/index.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top"><%= site_name %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a class="page-scroll call-button" href="tel:+4152002278" data-ga-label="call0">Call (415) 200-2278</a>
        </li>
        <li class="no-focus">
          <a class="page-scroll quote-req" href="#" data-toggle="modal" data-target="#myModal" data-ga-label="quote0">Get Free Quote Now</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<header>
  <div class="header-content">
    <div class="header-content-inner">
      <h1>Funeral Planning To Put You At Ease</h1>
      <hr class="primary">
      <br />
      <br />
      <br />
      <br />
      <p>Step-by-step guidance and family-quality care for your loved ones during the toughest of times.</p>
      <a href="#" class="btn btn-action action btn-xl page-scroll no-focus quote-req" data-ga-label="quote1" data-toggle="modal" data-target="#myModal">Get Free Quote Now</a>
      <br />
      <br />
      <a href="tel:+4152002278" class="btn btn-alternate btn-xl page-scroll call-button" data-ga-label="call1">Call (415) 200-2278</a>
    </div>
  </div>
</header>

<section class="bg-primary" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">We've got you covered!</h2>
        <hr class="light-fade">
        <p class="text-faded">Respectful will take care of all your end of life needs from start to finish, allowing you to honor your loved ones and spend time with with those closest to you at such a vital time. You shouldn't have to deal with the stress of planning a funeral, we'll take care of it. </p>
        <!-- <a href="#" class="btn btn-default btn-xl">Get Started!</a> -->
      </div>
      <div class="row">
      <div class="col-md-6 text-center buttons">
        <a href="#" class="btn btn-action btn-xl page-scroll quote-req" data-ga-label="quote2" data-toggle="modal" data-target="#myModal">Get Free Quote Now</a>
      </div>
      <div class="col-md-6 text-center buttons">
        <a href="tel:+4152002278" class="btn btn-default btn-xl page-scroll call-button" data-ga-label="call2">Call (415) 200-2278</a>
      </div>
    </div>
    </div>
  </div>
</section>

<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Here's how Respectful works</h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-check wow bounceIn text-primary"></i>
          <h3>We Help You Plan</h3>
          <p class="text-muted">Easily understand your options and plan the best funeral.</p>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-list-ol wow bounceIn text-primary" data-wow-delay=".1s"></i>
          <h3>We Handle the Details</h3>
          <p class="text-muted">Our experts work with providers to negotiate the best prices and execute your wishes.</p>
        </div>
      </div>
      <div class="col-lg-4 col-md-12 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-users wow bounceIn text-primary" data-wow-delay=".2s"></i>
          <h3>Honor Your Loved One</h3>
          <p class="text-muted">The first time you deal with a funeral home is when you honor your loved one.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <br>
    <br>
    <div class="row">
      <div class="col-md-6 text-center buttons">
        <a href="#" class="btn btn-action action btn-xl page-scroll quote-req" data-ga-label="quote3" data-toggle="modal" data-target="#myModal">Get Free Quote Now</a>
      </div>
      <div class="col-md-6 text-center buttons">
        <a href="tel:+4152002278" class="btn btn-primary btn-xl page-scroll call-button" data-ga-label="call3">Call (415) 200-2278</a>
      </div>
    </div>
  </div>
</section>

<aside class="bg-dark">
  <div class="container text-center">
    <div class="call-to-action">
      <h2>Respectful saves you time, money, and stress.</h2>
    </div>
    <hr class="light-fade">
    <div class="col-lg-4 col-sm-6 box-text wow fadeIn" data-wow-delay=".1s">
        <div class="portfolio-box">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category">
                Step-by-step guidance.
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 box-text wow fadeIn" data-wow-delay=".2s">
        <div class="portfolio-box">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category">
                The exact funeral you want
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 box-text wow fadeIn" data-wow-delay=".3s">
        <div class="portfolio-box">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category">
                Expertly negotiated price
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 box-text wow fadeIn" data-wow-delay=".4s">
        <div class="portfolio-box">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category">
                Full service concierge
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 box-text wow fadeIn" data-wow-delay=".5s">
        <div class="portfolio-box">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category">
                Easily share details with family
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 box-text wow fadeIn" data-wow-delay=".6s">
        <div class="portfolio-box">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category">
                Peace of mind and grieving time your deserve
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="row">
      <div class="col-md-6 text-center buttons">
        <a href="#" class="btn btn-action btn-xl wow pulse quote-req" data-ga-label="quote4" data-toggle="modal" data-target="#myModal">Get Free Quote Now</a>
      </div>
      <div class="col-md-6 text-center buttons">
        <a href="tel:+4152002278" class="btn btn-default btn-xl wow pulse call-button" data-ga-label="call4">call (415) 200-2278</a>
      </div>
    </div>
  </div>
</aside>

<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">Let's Get In Touch!</h2>
        <hr class="primary">
        <p>Ready to start planning an end of life service? Give us a call or send us and email and we'll get back to you as soon as possible!</p>
      </div>
      <div class="col-lg-4 col-lg-offset-2 text-center">
        <i class="fa fa-phone fa-3x wow bounceIn"></i>
        <p><a href="tel:+4152002278" class="call-button" data-ga-label="call5">(415) 200-2278</a></p>
      </div>
      <div class="col-lg-4 text-center">
        <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
        <p><a href="mailto:info@joinrespectful.com">info@joinrespectful.com</a></p>
      </div>
    </div>
  </div>
</section>

  <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div id="lead-modal" class="modal-body row">
        <div class="header">
          <h2 class="modal-title text-center" id="myModalLabel">Save time, money, and stress!</h2>
        </div>
        <%= form_for Lead.new, remote: true, url: new_lead_path,  method: :put do |f| %>
          <div class="col-md-8 col-md-offset-2">
            <%= f.text_field :name, placeholder: 'Name', class: 'form-control form-input required' %>
          </div>
          <div class="col-md-8 col-md-offset-2">
            <%= f.text_field :phone_number, id: 'phone-input', placeholder: 'Number', class: 'form-control form-input required' %>
          </div>
          <div class="col-md-12 text-center">
            <br />
            <%= f.submit 'Get Your Free Quote', class: "btn btn-action btn-lg btn-unrounded", id: "quote-submit", data: { ga_label: "request0" }%>
          </div>
        <% end -%>
      </div>
    </div>
  </div>
</div>