config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :admins
  devise_for :user
  root to: 'landing#index'

  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  put '/lead_new' => 'leads#create', as: :new_lead

  mount RailsAdmin::Engine => '/administer', as: 'rails_admin'
  namespace :admin do

    root to: 'leads#index'
    resources :leads, only: [:index]
    resources :users
    resources :burial_plans, only: [:new, :create, :edit, :update]
    get '/upgrade_lead' => 'leads#upgrade_form', as: :lead_upgrade_form
    post '//upgrade_lead' => 'leads#upgrade', as: :lead_upgrade
    get '/call' => 'calls#index', as: :call
    post '/call' => 'calls#create_call'
    get '/call_connect' => 'call_connect#index'
    post '/place_call_connect' => 'call_connect#create', as: :place_call_connect

    devise_scope :admins do
    get '/login'   => 'devise/sessions#new', id: 'login'
    post 'login'   => 'devise/sessions#create'
    delete 'logout'=> 'devise/sessions#destory', id: 'logout'
    end
  end

  namespace :user do
    root to:'users#show'
    resources :after_signup
    resources :burial_plans
    resources :burial_cemetery_plans
    resources :burial_mausoleum_plans
    resources :cremation_plans
    # get '/registration'      => 'users#registration'
    # patch '/registration/update' => 'users#update', as: :registration_update
    get '/plans/new' => 'plans#new', as: :plan_new
    # patch '/burial_plans/update' => 'burial_plans#update', as: :burial_update
    # get '/burial_plans/new' => 'burial_plans#new', as: :burial_new
    # patch '/cremation_plans/update' => 'cremation_plans#update', as: :cremation_update
    # get '/cremation_plans/new' => 'cremation_plans#new', as: :cremation_new
    # get '/burial_cemetery_plan/new' => 'burial_cemetery_plans#new', as: :burial_cemetery_new
    # patch '/burial_cemetery/update' => 'burial_cemetery_plans#update', as: :burial_cemetery_update
    # get '/burial_mausoleum_plan/new' => 'burial_mausoleum_plans#new', as: :burial_mausoleum_new
    # patch '/burial_mausoleum/update' => 'burial_mausoleum_plans#update', as: :burial_mausoleum_update



  devise_scope :user do
    get 'signup'   => 'devise/registrations#new', id: 'signup'
    get '/login'   => 'devise/sessions#new', id: 'login'
    post 'login'   => 'devise/sessions#create'
    delete 'logout'=> 'devise/sessions#destory', id: 'logout'
  end

  end


  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :passings, dependent: :delete_all, inverse_of: :user
  has_many :burial_plans, through: :passings
  has_many :cremation_plans, through: :passings
  has_many :burial_mausoleum_plans, through: :burial_plans
  has_many :burial_cemetery_plans, through: :burial_plans
  has_one :lead, dependent: :destroy
  has_one :passing_address, through: :passing


  accepts_nested_attributes_for :passings, :burial_plans, :cremation_plans, :burial_cemetery_plans, :burial_mausoleum_plans, reject_if: :all_blank, allow_destroy: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, only: [:edit, :update, :destroy, :show]

  def index
    @users = User.order(created_at: :desc).page(params[:page])
  end

  def edit
    js :new
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "#{@user.full_name} saved"
      redirect_to [:admin, @user]
    else
      render :edit
    end
  end

  def destroy

  end

  def show
    js :new
  end

  private

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit!
  end
end

app/controllers/user/after_signup_controller.rb
class User::AfterSignupController < User::BaseController
  include Wicked::Wizard
  steps :basic_info, :passing_name, :passing_relation, :passing_dates, :passing_location, :start_planning
  before_action :load_user_and_passing

  def show
    @user = current_user
    render_wizard
  end

  def update
    @user.update_attributes(user_attributes)
    render_wizard @user
  end

  private

  def load_user_and_passing
    @user = current_user
    if @user.passings.present?
      @passing = @user.passings.last
    else
      @passing = @user.passings.build
    end
  end

  def user_attributes
    params.require(:user).permit!
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_action :authenticate_user!

  layout 'user'
end

app/controllers/user/burial_cemetery_plans_controller.rb
class User::BurialCemeteryPlansController < User::BaseController
  before_action :load_user
  before_action :load_cemetery_plan, only: [ :edit, :update, :destroy]

  def new
    @passing = @user.passings.last
    @burial = @passing.burial_plans.last
    @cemetery_plan = @burial.burial_cemetery_plans.build
    if @cemetery_plan.save
      respond_to do |format|
        format.js
      end
    end
  end

  def update
    @cemetery_plan.update_attributes(cemetery_params)
    render nothing: true
    # if @burial.burial_space_owned || @burial.burial_space_owned == false
    #   respond_to do |format|
    #     format.js
    #   end
    # else
    #   render nothing: true
    # end
  end

  private

  def load_user
    @user = current_user
  end

  def load_cemetery_plan
    @cemetery_plan = BurialCemeteryPlan.find(params[:burial_cemetery_plan][:id])
  end

  def cemetery_params
    params.require(:burial_cemetery_plan).permit!
  end
end

app/controllers/user/burial_mausoleum_plans_controller.rb
class User::BurialMausoleumPlansController < User::BaseController
  before_action :load_user
  before_action :load_mausoleum_plan, only: [ :edit, :update, :destroy]
  def new
    @passing = @user.passings.last
    @burial = @passing.burial_plans.last
    @mausoleum_plan = @burial.burial_mausoleum_plans.build
    if @mausoleum_plan.save
      respond_to do |format|
        format.js
      end
    end
  end

  def update
    @mausoleum_plan.update_attributes(mausoleum_params)
    if @burial.burial_space_owned || @burial.burial_space_owned == false
      respond_to do |format|
        format.js
      end
    else
      render nothing: true
    end
  end

  private

  def load_user
    @user = current_user
  end

  def load_mausoleum_plan
    @mausoleum_plan = BurialMausoleumPlan.find(params[:burial_mausoleum_plan][:id])
  end

  def mausoleum_params
    params.require(:burial_mausoleum_plan).permit!
  end
end

app/controllers/user/burial_plans_controller.rb
class User::BurialPlansController < User::BaseController
  include Wicked::Wizard
  steps :plan_dates, :public_service, :open_casket,  :private_viewing, :type_of_service, :religion_culture_type, :type_of_service_space, :worship_space_in_mind, :location_of_worship_space, :worship_plan_later, :address_of_service_space, :burial_site_in_mind, :burial_types_of_plans, :location_of_burial_site, :burial_space_owned
  before_action :load_user_and_passing

  def show
    case step
    when :plan_dates
      @burial.plan_dates.build
    when :address_of_service_space
      @burial.build_service_space_address
    when :location_of_burial_site
      @burial.build_burial_space_address
    end
    render_wizard
  end

  def update
    @burial.update_attributes(burial_params)
    render_wizard @burial
  end

  private

  def load_user_and_passing
    @user = current_user
    @passing = @user.passings.last
    @burial = @passing.burial_plans.last
  end

  def burial_params
    params.require(:burial_plan).permit!
  end
end

app/controllers/user/cremation_plans_controller.rb
class User::CremationPlansController < User::BaseController
  before_action :load_user
  before_action :load_cremation, only: [:edit, :update, :destroy]

  def index

  end

  def new
    @passing = @user.passings.last
    @cremation = @passing.cremation_plans.build
    if @cremation.save
      respond_to do |format|
        @cremation.build_service_space_address
        @cremation.build_ash_storage_address
        @cremation.build_ash_delivery_address
        @cremation.plan_dates.build
        format.js
      end
    end
  end

  def update
    @cremation.update_attributes(cremation_params)


    render nothing: true
  end

  private

  def load_user
    @user = current_user
  end

  def load_cremation
    @cremation = CremationPlan.find(params[:cremation_plan][:id])
  end

  def cremation_params
    params.require(:cremation_plan).permit!
  end

end

app/controllers/user/plans_controller.rb
class User::PlansController < User::BaseController

  def index
    respond_to do |format|
      format.js
    end
  end

  def new
  end

end

app/controllers/user/users_controller.rb
class User::UsersController < User::BaseController

  def show
    @user = current_user
  end

  def update
    @user = current_user
    @user.registered = true
    @user.update_attributes(user_params)

    respond_to do |format|
      format.js
    end
  end

  # def final_registration
  #   respond_to do |format|
  #     format.js { render 'registration.js.erb'}
  #   end
  # end

  def registration
    @user = current_user
    if @user.passings.present?
      @passing = @user.passings.last
    else
      @passing = @user.passings.build
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :phone_number, passings_attributes:[:first_name, :last_name, :relation, :date_of_birth, :date_of_passing, :location_of_passing, :address_of_passing])
  end

end

app/views/user/users/_registration_form.html.erb
<%= form_for @user, remote: true, url: user_registration_update_path, html: {id: "user-registration-form", method: :patch } do |f| %>
  <h3>Info</h3>
  <fieldset>
    <legend>Profile Information</legend>
    <div class="row">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>Let's get started by getting to know you.</span>
      </div>
      <div class="error col-md-12 col-sm-12 col-xs-12">
        <span></span>
      </div>

      <br>

      <div class="col-md-6 col-sm-6 col-xs-12 text-left">
        <%= f.label :first_name, 'First Name *', class: 'form-label' %><br />
        <%= f.text_field :first_name, class: 'form-control required' %>
        <br>
        <%= f.label :last_name, 'Last Name *', class: 'form-label' %><br />
        <%= f.text_field :last_name, class: 'form-control required' %>
        <br>
        <%= f.label :phone_number, 'Phone Number *', class: 'form-label' %><br />
        <%= f.text_field :phone_number, class: 'form-control required number' %>
        <br>

        <p class="form-label">(*) Mandatory</p>

      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>

    </div>
  </fieldset>

  <h3>Name</h3>
  <fieldset>
    <legend>Loved one's name</legend>
    <div class="row">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>What's the name of the loved one you're planning for?</span>
      </div>

      <br>

      <div class="col-md-6 col-sm-6 col-xs-12 text-left">
        <%= f.fields_for :passings, @passing do |b| %>
          <%= b.label :first_name, 'First Name *', class: 'form-label' %><br />
          <%= b.text_field :first_name, id: 'passing_name', class: 'form-control required'%>
          <br>
          <%= b.label :last_name, 'Last Name *', class: 'form-label' %><br />
          <%= b.text_field :last_name, class: 'form-control required' %>
          <br>

        <p class="form-label">(*) Mandatory</p>

      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>

    </div>
  </fieldset>


  <h3>Relation</h3>
  <fieldset>
    <legend>Relation to Loved On</legend>
    <div class="row">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>We're sorry to head about <span class="loved-one-name"></span>'s passing.</span>
      </div>
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>How were you related?</span>
      </div>

      <br>

      <div class="radios col-md-6 col-sm-6 col-xs-12">
        <div class="center-block">
        <%= b.label :relation, value: 'spouse/partner', class: '' do %>
          <div class="label-text"> Spouse/Partner </div>
        <% end -%>
        <%= b.radio_button :relation, 'spouse/partner' %>

        <%= b.label :relation, value: 'child', class: '' do %>
          <div class="label-text"> Child </div>
        <% end -%>
        <%= b.radio_button :relation, 'child' %>

        <%= b.label :relation, value: 'sibling', class: '' do %>
          <div class="label-text"> Sibling</div>
        <% end -%>
        <%= b.radio_button :relation, 'sibling' %>

        <%= b.label :relation, value: 'parent', class: '' do %>
          <div class="label-text"> Parent </div>
        <% end -%>
        <%= b.radio_button :relation, 'parent' %>

        <%= b.label :relation, value: 'other family', class: '' do %>
          <div class="label-text"> Other Family </div>
        <% end -%>
        <%= b.radio_button :relation, 'other family' %>

        <%= b.label :relation, value: 'other', class: '' do %>
          <div class="label-text"> Other </div>
        <% end -%>
        <%= b.radio_button :relation, 'other' %>
      </div>
      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>

    </div>
  </fieldset>
  <h3>Dates</h3>
    <fieldset>
      <legend>Date Information</legend>
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12 text-left">

          <div class="form-group">
            <%= b.label :date_of_birth, 'When was <span class="loved-one-name"/></span> born?'.html_safe, class: 'form-label' %><br />
            <div class="input-group">
              <%= b.date_select :date_of_birth, prompt: { day: 'day', month: 'month', year: 'year' }, start_year: 1910, end_year: Date.today.year %>
            </div>
          </div>
          <br />
          <div class="form-group">
            <%= b.label :date_of_passing, 'When did <span class="loved-one-name"></span> pass?'.html_safe, class: 'form-label' %><br />
            <div class="input-group">
              <%= b.text_field :date_of_passing, class: 'form-control datetimepicker' %>
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
          <br />
        </div>
        <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
          <aside class="frame">
            <ul>
              <li class="frame-head">
                <div class="center">
                  Help!
                </div>
              </li>
              <li class="disc-item">
                we hope to help you in whichever way we can
              </li>
            </ul>

          </aside>
        </div>

      </div>
    </fieldset>
  <h3>Location</h3>
    <fieldset>
      <legend><span class="loved-one-name"/></span>'s Location</legend>

      <div class="row">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>And currently where is <span class="loved-one-name"></span> ?</span>
      </div>

      <br>

      <div class="col-md-6 col-sm-6 col-xs-12 text-left btn-group", data-toggle: "buttons">

        <div>
        <label>
          <%= b.radio_button :location_of_passing, 'Hospital' %> Hospital
        </label>
        </div>
        <br />
        <div>
        <label>
          <%= b.radio_button :location_of_passing, 'Home' %> Home
        </label>
        </div>
        <br />
        <div>
        <label>
          <%= b.radio_button :location_of_passing, 'Hospice' %> Hospice
        </label>
        </div>
        <br />
        <div>
        <label>
          <%= b.radio_button :location_of_passing, 'Other Location' %> Other Location
        </label>
        </div>

      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>
      <% end %>
    </div>
    </fieldset>
  <h3>Finish</h3>
    <fieldset>
      <div id="update-response">
      </div>
    </fieldset>
  <% end %>

app/views/user/users/_update.html.erb
  <div class="row">
    <div class="header col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="col-md-2 col-md-offset-5 col-sm-2 col-sm-offset-5 col-xs-12"> <i class="fa fa-check"></i></div>

      </div>
      <span>Thanks for helping with the basics.</span>
    </div>

    <br/>

    <div class="subtext col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
      <span> Now we'll help walk you through everything you'll need to know to plan a service.</span>
      <br/>
      <hr>
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <button id="get-started" type="button" class="btn btn-primary btn-unrounded btn-block">Start Planning</button>
        </div>
      </div>
    </div>
  </div>

app/views/user/users/registration.js.erb
$('#registration').html("<%= j render('registration_form', locals: { user: @user} ) %>");

var form = $("#user-registration-form").show();

form.steps({
  headerTag: "h3",
  bodyTag: "fieldset",
  transitionEffect: "slideLeft",
  saveState: true,
  enableFinishButton: false,
  onStepChanging: function (event, currentIndex, newIndex)
  {
    // Allways allow previous action even if the current form is not valid!
    if (currentIndex > newIndex)
    {
        return true;
    }
    // Needed in some cases if the user went back (clean up)
    if (currentIndex < newIndex)
    {
      // To remove error styles
      form.find(".body:eq(" + newIndex + ") label.error").remove();
      form.find(".body:eq(" + newIndex + ") .error").removeClass("error");
    }

    form.validate().settings.ignore = ":disabled,:hidden";
    return form.valid();
  },
  onStepChanged: function (event, currentIndex, priorIndex)
  {
    // add passings name when the user adds it.
    if (currentIndex >= 2)
    {
      var Name = $("#passing_name").val();
      $(".loved-one-name").text(Name);
    }

       if (currentIndex === 5)
    {
      $('form#user-registration-form').submit();
    }

    if (currentIndex === 6)
    {
      enablePagination: false;
    }
  },
  onInit: function (event, currentIndex)
  {
    if (currentIndex === 6)
    {
      $.get( "/users/registration_final" );
    }

  }
}).validate({
  errorPlacement: function errorPlacement(error, element) { element.before(error); },
  rules: {
  }
});


// $('input:radio').addClass('input_hidden');
// $('label').click(function() {
//     $(this).addClass('radio-selected').siblings().removeClass('radio-selected');
// });

app/views/user/users/show.html.erb
<div id="user-tabs">
  <ul>
    <li><a href="#tabs-1">Info</a></li>
    <li><a href="#tabs-2">Plan</a></li>
    <li><a href="#tabs-3">Dessert</a></li>
  </ul>
  <div id="tabs-1">
    <div id="registration">
    </div>
  </div>
  <div id="tabs-2">
    <div id="passing-plan">

    </div>

  </div>
  <div id="tabs-3">
    <p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
    <p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. Nam scelerisque. Donec non libero sed nulla mattis commodo. Ut sagittis. Donec nisi lectus, feugiat porttitor, tempor ac, tempor vitae, pede. Aenean vehicula velit eu tellus interdum rutrum. Maecenas commodo. Pellentesque nec elit. Fusce in lacus. Vivamus a libero vitae lectus hendrerit hendrerit.</p>
  </div>
</div>

app/views/user/users/update.js.erb
$('#update-response').html("<%= j render('update').html_safe %>");
// $('user-registration-form').steps("add", {
  //   title: "Finished!",
  //   content: "This is a test"
  // })
$('#get-started').click(function() { // bind click event to link
  $.get('<%= user_plan_new_path %>');
  $("#user-tabs").tabs("option", "active", 1 );
});