config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :admins
  devise_for :user
  root to: 'landing#index'

  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  put '/lead_new' => 'leads#create', as: :new_lead

  mount RailsAdmin::Engine => '/administer', as: 'rails_admin'
  namespace :admin do

    root to: 'leads#index'
    resources :leads, only: [:index]
    resources :users
    resources :burial_plans, only: [:new, :create, :edit, :update]
    get '/upgrade_lead' => 'leads#upgrade_form', as: :lead_upgrade_form
    post '//upgrade_lead' => 'leads#upgrade', as: :lead_upgrade
    get '/call' => 'calls#index', as: :call
    post '/call' => 'calls#create_call'
    get '/call_connect' => 'call_connect#index'
    post '/place_call_connect' => 'call_connect#create', as: :place_call_connect

    devise_scope :admins do
    get '/login'   => 'devise/sessions#new', id: 'login'
    post 'login'   => 'devise/sessions#create'
    delete 'logout'=> 'devise/sessions#destory', id: 'logout'
    end
  end

  namespace :user do
    root to:'users#show'
    resources :after_signup
    resources :burial_plans
    resources :burial_cemetery_plans
    resources :burial_mausoleum_plans
    resources :cremation_plans
    # get '/registration'      => 'users#registration'
    # patch '/registration/update' => 'users#update', as: :registration_update
    get '/plans/new' => 'plans#new', as: :plan_new
    # patch '/burial_plans/update' => 'burial_plans#update', as: :burial_update
    # get '/burial_plans/new' => 'burial_plans#new', as: :burial_new
    # patch '/cremation_plans/update' => 'cremation_plans#update', as: :cremation_update
    # get '/cremation_plans/new' => 'cremation_plans#new', as: :cremation_new
    # get '/burial_cemetery_plan/new' => 'burial_cemetery_plans#new', as: :burial_cemetery_new
    # patch '/burial_cemetery/update' => 'burial_cemetery_plans#update', as: :burial_cemetery_update
    # get '/burial_mausoleum_plan/new' => 'burial_mausoleum_plans#new', as: :burial_mausoleum_new
    # patch '/burial_mausoleum/update' => 'burial_mausoleum_plans#update', as: :burial_mausoleum_update



  devise_scope :user do
    get 'signup'   => 'devise/registrations#new', id: 'signup'
    get '/login'   => 'devise/sessions#new', id: 'login'
    post 'login'   => 'devise/sessions#create'
    delete 'logout'=> 'devise/sessions#destory', id: 'logout'
  end

  end


  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'

end

app/models/burial_plan.rb
class BurialPlan < ActiveRecord::Base
  belongs_to :passing, inverse_of: :burial_plans
  has_many :plan_dates, as: :dateable, dependent: :delete_all
  has_many :burial_cemetery_plans, dependent: :delete_all, inverse_of: :burial_plan
  has_many :burial_mausoleum_plans, dependent: :delete_all, inverse_of: :burial_plan

  has_one :service_space_address, -> { where(type_of: 'service space') }, as: :addressable, class_name: :Address, dependent: :destroy
  has_one :burial_space_address, -> { where(type_of: 'burial space') }, as: :addressable, class_name: :Address, dependent: :destroy

  validates :passing, presence: true

  accepts_nested_attributes_for :plan_dates, :service_space_address, :burial_space_address
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :passings, dependent: :delete_all, inverse_of: :user
  has_many :burial_plans, through: :passings
  has_many :cremation_plans, through: :passings
  has_many :burial_mausoleum_plans, through: :burial_plans
  has_many :burial_cemetery_plans, through: :burial_plans
  has_one :lead, dependent: :destroy
  has_one :passing_address, through: :passing


  accepts_nested_attributes_for :passings, :burial_plans, :cremation_plans, :burial_cemetery_plans, :burial_mausoleum_plans, reject_if: :all_blank, allow_destroy: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/burial_plans_controller.rb
class Admin::BurialPlansController < Admin::BaseController
  before_action :load_burial, only: [:edit, :update, :destroy, :show]

  def new
    @passing = Passing.find(params[:passing_id])
    @burial = @passing.burial_plans.build
  end

  def edit

  end

  def update
    if @burial.update_attributes(burial_params)
      flash[:success] = "Burial Plan saved"
      redirect_to admin_user_path(@burial.passing.user)
    else
      render :edit
    end
  end

  private

  def load_burial
    @burial = BurialPlan.find(params[:id])
  end

  def burial_params
    params.require(:burial_plan).permit!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, only: [:edit, :update, :destroy, :show]

  def index
    @users = User.order(created_at: :desc).page(params[:page])
  end

  def edit
    js :new
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "#{@user.full_name} saved"
      redirect_to [:admin, @user]
    else
      render :edit
    end
  end

  def destroy

  end

  def show
    js :new
  end

  private

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit!
  end
end

app/controllers/user/after_signup_controller.rb
class User::AfterSignupController < User::BaseController
  include Wicked::Wizard
  steps :basic_info, :passing_name, :passing_relation, :passing_dates, :passing_location, :start_planning
  before_action :load_user_and_passing

  def show
    @user = current_user
    render_wizard
  end

  def update
    @user.update_attributes(user_attributes)
    render_wizard @user
  end

  private

  def load_user_and_passing
    @user = current_user
    if @user.passings.present?
      @passing = @user.passings.last
    else
      @passing = @user.passings.build
    end
  end

  def user_attributes
    params.require(:user).permit!
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_action :authenticate_user!

  layout 'user'
end

app/controllers/user/burial_cemetery_plans_controller.rb
class User::BurialCemeteryPlansController < User::BaseController
  before_action :load_user
  before_action :load_cemetery_plan, only: [ :edit, :update, :destroy]

  def new
    @passing = @user.passings.last
    @burial = @passing.burial_plans.last
    @cemetery_plan = @burial.burial_cemetery_plans.build
    if @cemetery_plan.save
      respond_to do |format|
        format.js
      end
    end
  end

  def update
    @cemetery_plan.update_attributes(cemetery_params)
    render nothing: true
    # if @burial.burial_space_owned || @burial.burial_space_owned == false
    #   respond_to do |format|
    #     format.js
    #   end
    # else
    #   render nothing: true
    # end
  end

  private

  def load_user
    @user = current_user
  end

  def load_cemetery_plan
    @cemetery_plan = BurialCemeteryPlan.find(params[:burial_cemetery_plan][:id])
  end

  def cemetery_params
    params.require(:burial_cemetery_plan).permit!
  end
end

app/controllers/user/burial_mausoleum_plans_controller.rb
class User::BurialMausoleumPlansController < User::BaseController
  before_action :load_user
  before_action :load_mausoleum_plan, only: [ :edit, :update, :destroy]
  def new
    @passing = @user.passings.last
    @burial = @passing.burial_plans.last
    @mausoleum_plan = @burial.burial_mausoleum_plans.build
    if @mausoleum_plan.save
      respond_to do |format|
        format.js
      end
    end
  end

  def update
    @mausoleum_plan.update_attributes(mausoleum_params)
    if @burial.burial_space_owned || @burial.burial_space_owned == false
      respond_to do |format|
        format.js
      end
    else
      render nothing: true
    end
  end

  private

  def load_user
    @user = current_user
  end

  def load_mausoleum_plan
    @mausoleum_plan = BurialMausoleumPlan.find(params[:burial_mausoleum_plan][:id])
  end

  def mausoleum_params
    params.require(:burial_mausoleum_plan).permit!
  end
end

app/controllers/user/burial_plans_controller.rb
class User::BurialPlansController < User::BaseController
  include Wicked::Wizard
  steps :plan_dates, :public_service, :open_casket,  :private_viewing, :type_of_service, :religion_culture_type, :type_of_service_space, :worship_space_in_mind, :location_of_worship_space, :worship_plan_later, :address_of_service_space, :burial_site_in_mind, :burial_types_of_plans, :location_of_burial_site, :burial_space_owned
  before_action :load_user_and_passing

  def show
    case step
    when :plan_dates
      @burial.plan_dates.build
    when :address_of_service_space
      @burial.build_service_space_address
    when :location_of_burial_site
      @burial.build_burial_space_address
    end
    render_wizard
  end

  def update
    @burial.update_attributes(burial_params)
    render_wizard @burial
  end

  private

  def load_user_and_passing
    @user = current_user
    @passing = @user.passings.last
    @burial = @passing.burial_plans.last
  end

  def burial_params
    params.require(:burial_plan).permit!
  end
end

app/controllers/user/cremation_plans_controller.rb
class User::CremationPlansController < User::BaseController
  before_action :load_user
  before_action :load_cremation, only: [:edit, :update, :destroy]

  def index

  end

  def new
    @passing = @user.passings.last
    @cremation = @passing.cremation_plans.build
    if @cremation.save
      respond_to do |format|
        @cremation.build_service_space_address
        @cremation.build_ash_storage_address
        @cremation.build_ash_delivery_address
        @cremation.plan_dates.build
        format.js
      end
    end
  end

  def update
    @cremation.update_attributes(cremation_params)


    render nothing: true
  end

  private

  def load_user
    @user = current_user
  end

  def load_cremation
    @cremation = CremationPlan.find(params[:cremation_plan][:id])
  end

  def cremation_params
    params.require(:cremation_plan).permit!
  end

end

app/controllers/user/plans_controller.rb
class User::PlansController < User::BaseController

  def index
    respond_to do |format|
      format.js
    end
  end

  def new
  end

end

app/controllers/user/users_controller.rb
class User::UsersController < User::BaseController

  def show
    @user = current_user
  end

  def update
    @user = current_user
    @user.registered = true
    @user.update_attributes(user_params)

    respond_to do |format|
      format.js
    end
  end

  # def final_registration
  #   respond_to do |format|
  #     format.js { render 'registration.js.erb'}
  #   end
  # end

  def registration
    @user = current_user
    if @user.passings.present?
      @passing = @user.passings.last
    else
      @passing = @user.passings.build
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :phone_number, passings_attributes:[:first_name, :last_name, :relation, :date_of_birth, :date_of_passing, :location_of_passing, :address_of_passing])
  end

end

app/views/user/burial_plans/_update_1.html.erb
 <div class="row">
    <div class="header col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="col-md-2 col-md-offset-5 col-sm-2 col-sm-offset-5 col-xs-12"></div>

      </div>
      <span>Thanks! That'll definitely help speed things up.</span>
    </div>

    <br/>

    <div class="subtext col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
      <span> Send out your information now to Funeral Homes near by. Soon we'll be able to give you a price quote.</span>
      <br/>
      <hr>
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <button id="get-started" type="button" class="btn btn-primary btn-unrounded btn-block">Send to Funeral Homes</button>
        </div>
      </div>
    </div>
  </div>

app/views/user/burial_plans/_update_2.html.erb
 <div class="row">
    <div class="header col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="col-md-2 col-md-offset-5 col-sm-2 col-sm-offset-5 col-xs-12"></div>

      </div>
      <span>No worries. This is something that your funeral director can always help you with.</span>
    </div>

    <br/>

    <div class="subtext col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
      <span> Send out your information now to Funeral Homes near by. Soon we'll be able to give you a price quote.</span>
      <br/>
      <hr>
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <button id="get-started" type="button" class="btn btn-primary btn-unrounded btn-block">Send to Funeral Homes</button>
        </div>
      </div>
    </div>
  </div>

app/views/user/burial_plans/burial_site_in_mind.html.erb
<div class="wizard">
  <%= form_for @burial, url: wizard_path,  method: :put do |f| %>
    <legend>Burial Space</legend>
    <div class="row content">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span><em>High 5</em> You're doing a great job! Let's keep moving.</span>
      </div>
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>Do you have a burial site in mind?</span>
      </div>

      <br>

      <div class="col-md-6 col-sm-6 col-xs-12 text-left">
        <div class= "radios">
          <%= f.radio_button :burial_space_in_mind, true, class: 'input-hidden' %>
          <%= f.label :burial_space_in_mind, value: true, class: '' do %>
            <div class="label-text"> Yes </div>
          <% end -%>

          <%= f.radio_button :burial_space_in_mind, false, class: 'input-hidden' %>
          <%= f.label :burial_space_in_mind, value: false, class: '' do %>
            <div class="label-text"> No </div>
          <% end -%>
        </div>
        <p class="form-label">(*) Mandatory</p>

      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-3 pull-left actions">
        <%= link_to "Back", previous_wizard_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3 pull-right actions">
        <%= f.submit "Next", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end -%>
</div>

app/views/user/burial_plans/burial_types_of_plans.html.erb
<div class="wizard">
  <legend>Worship Space</legend>
  <div class="row content">
    <div class="header col-md-12 col-sm-12 col-xs-12">
      <span>No sweat. Most people don't.</span>
    </div>
    <div class="header col-md-12 col-sm-12 col-xs-12">
      <span>We can help you plan.</span>
    </div>
    <br>
    <div class="subtext col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
      <span> Would sort of plan are you thinking? </span>
      <br/>
      <hr>
      <div class="row">
        <div class="col-xs-5">
          <button id="get-burial-cemetery" type="button" class="btn btn-primary btn-unrounded btn-block"><%= link_to 'Cemetery Plan', user_burial_cemetery_plans_path %></button>
        </div>
        <div class="col-xs-5 col-xs-offset-2">
          <button id="get-burial-mausoleum" type="button" class="btn btn-primary btn-unrounded btn-block"><%= link_to 'Mausoleum Plan', user_burial__mausoleum_plans_path %></button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/burial_plans/location_of_burial_site.html.erb
<div class="wizard">
  <%= form_for @burial, url: wizard_path,  method: :put do |f| %>
    <legend>Burial Space</legend>
    <div class="row content">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>What's the address?</span>
      </div>
      <div class="header col-md-12 col-sm-12 col-xs-12">
      </div>
      <br>
      <div class="col-md-6 col-sm-6 col-xs-12 text-left">
        <%= f.fields_for :burial_space_address do |address| %>
            <%= render partial: 'shared/address', locals: { f: address } %>
          <% end -%>
      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-3 pull-left actions">
        <%= link_to "Back", previous_wizard_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3 pull-right actions">
        <%= f.submit "Next", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end -%>
</div>

app/views/user/burial_plans/location_of_worship_space.html.erb
<div class="wizard">
  <%= form_for @burial, url: wizard_path,  method: :put do |f| %>
    <legend>Worship Space</legend>
    <div class="row content">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>Sounds special.</span>
      </div>
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>Which worship space are you thinking about?</span>
      </div>

      <br>

      <div class="col-md-6 col-sm-6 col-xs-12 text-left">
        <div class= "dropdowns">
          <%= f.collection_select :worship_space, WorshipSpace.order(:name),:name,:name, include_blank: true, class: 'form-control' %>

        </div>
        <p class="form-label">(*) Mandatory</p>

      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-3 pull-left actions">
        <%= link_to "Back", previous_wizard_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3 pull-right actions">
        <%= f.submit "Next", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end -%>
</div>

app/views/user/burial_plans/open_casket.html.erb
<div class="wizard">
  <%= form_for @burial, url: wizard_path,  method: :put do |f| %>
    <legend>Open or Closed Casket</legend>
    <div class="row content">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>What about an open casket?</span>
      </div>
      <div class="error col-md-12 col-sm-12 col-xs-12">
        <span></span>
      </div>

      <br>

      <div class="col-md-6 col-sm-6 col-xs-12 text-left">
        <div class= "radios">
          <%= f.radio_button :open_casket, true, class: 'input-hidden' %>
          <%= f.label :open_casket, value: true, class: '' do %>
            <div class="label-text"> Yes </div>
          <% end -%>

          <%= f.radio_button :open_casket, false, class: 'input-hidden' %>
          <%= f.label :open_casket, value: false, class: '' do %>
            <div class="label-text"> No </div>
          <% end -%>
        </div>
        <p class="form-label">(*) Mandatory</p>

      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-3 pull-left actions">
        <%= link_to "Back", previous_wizard_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3 pull-right actions">
        <%= f.submit "Next", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end -%>
</div>

app/views/user/burial_plans/private_viewing.html.erb
<div class="wizard">
  <%= form_for @burial, url: wizard_path,  method: :put do |f| %>
    <legend>Private Viewing</legend>
    <div class="row content">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>Would <%= @passing.first_name %>'s family like to have a private viewing before the service?</span>
      </div>
      <div class="error col-md-12 col-sm-12 col-xs-12">
        <span></span>
      </div>

      <br>

      <div class="col-md-6 col-sm-6 col-xs-12 text-left">
        <div class= "radios">
          <%= f.radio_button :private_viewing, true, class: 'input-hidden' %>
          <%= f.label :private_viewing, value: true, class: '' do %>
            <div class="label-text"> Yes </div>
          <% end -%>

          <%= f.radio_button :private_viewing, false, class: 'input-hidden' %>
          <%= f.label :private_viewing, value: false, class: '' do %>
            <div class="label-text"> No </div>
          <% end -%>
        </div>
        <p class="form-label">(*) Mandatory</p>

      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-3 pull-left actions">
        <%= link_to "Back", previous_wizard_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3 pull-right actions">
        <%= f.submit "Next", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end -%>
</div>

app/views/user/burial_plans/public_service.html.erb
<div class="wizard">
  <%= form_for @burial, url: wizard_path,  method: :put do |f| %>
    <legend>Type of service</legend>
    <div class="row content">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>Would you like a public service for <%= @passing.first_name %>?</span>
      </div>
      <div class="error col-md-12 col-sm-12 col-xs-12">
        <span></span>
      </div>

      <br>

      <div class="col-md-6 col-sm-6 col-xs-12 text-left">
        <div class= "radios">
          <%= f.radio_button :public_service, true, class: 'input-hidden' %>
          <%= f.label :public_service, value: true, class: '' do %>
            <div class="label-text"> Yes </div>
          <% end -%>

          <%= f.radio_button :public_service, false, class: 'input-hidden' %>
          <%= f.label :public_service, value: false, class: '' do %>
            <div class="label-text"> No </div>
          <% end -%>
        </div>
        <p class="form-label">(*) Mandatory</p>

      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-3 pull-left actions">
        <%= link_to "Back", previous_wizard_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3 pull-right actions">
        <%= f.submit "Next", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end -%>
</div>

app/views/user/burial_plans/religion_culture_type.html.erb
<div class="wizard">
  <%= form_for @burial, url: wizard_path,  method: :put do |f| %>
    <legend>Type of religion/culture</legend>
    <div class="row content">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>Sounds like a nice touch.</span>
      </div>
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>What type of culture or religion does <%= @passing.first_name %> identify with?</span>
      </div>

      <br>

      <div class="col-md-6 col-sm-6 col-xs-12 text-left">
        <div class= "dropdowns">
          <%= f.collection_select :religion_culture_type, Religion.order(:name),:name,:name, include_blank: true, class: 'form-control' %>
          <br />
          <%= f.collection_select :religion_culture_type, Culture.order(:name),:name,:name, include_blank: true, class: 'form-control' %>

        </div>
        <p class="form-label">(*) Mandatory</p>

      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-3 pull-left actions">
        <%= link_to "Back", previous_wizard_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3 pull-right actions">
        <%= f.submit "Next", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end -%>
</div>

app/views/user/burial_plans/type_of_service.html.erb
<div class="wizard">
  <%= form_for @burial, url: wizard_path,  method: :put do |f| %>
    <legend>Type of Service</legend>
    <div class="row content">
      <div class="header col-md-12 col-sm-12 col-xs-12">
        <span>Would <%= @passing.first_name %> like a religious or cultural service?</span>
      </div>
      <div class="error col-md-12 col-sm-12 col-xs-12">
        <span></span>
      </div>

      <br>

      <div class="col-md-6 col-sm-6 col-xs-12 text-left">
        <div class= "radios">
          <%= f.radio_button :religious_cultural_service, true, class: 'input-hidden' %>
          <%= f.label :religious_cultural_service, value: true, class: '' do %>
            <div class="label-text"> Yes </div>
          <% end -%>

          <%= f.radio_button :religious_cultural_service, false, class: 'input-hidden' %>
          <%= f.label :religious_cultural_service, value: false, class: '' do %>
            <div class="label-text"> No </div>
          <% end -%>
        </div>
        <p class="form-label">(*) Mandatory</p>

      </div>
      <div class="col-md-5 col-sm-5 col-sm-offset-1 col-xs-12">
        <aside class="frame">
          <ul>
            <li class="frame-head">
              <div class="center">
                Help!
              </div>
            </li>
            <li class="disc-item">
              we hope to help you in whichever way we can
            </li>
          </ul>

        </aside>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-3 pull-left actions">
        <%= link_to "Back", previous_wizard_path, class: 'btn btn-primary' %>
      </div>
      <div class="col-md-3 pull-right actions">
        <%= f.submit "Next", class: 'btn btn-primary' %>
      </div>
    </div>
  <% end -%>
</div>